apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  rules:
  - host: echo1.zemuldo.com
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
  - host: echo2.zemuldo.com
    http:
      paths:
      - backend:
          serviceName: echo2
          servicePort: 80